version: '3'

services:
  fetch:
    container_name: webpage_fetcher
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    command: bash -c "bundle install & tail -F anything"
